plugins {
	id("com.android.library") version("8.6.1")
}

ext.godotVersion = "4.7.1"

android {
	namespace "com.onecat.godottenjin"
	compileSdk 36
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}
	defaultConfig {
		minSdkVersion 24
		targetSdkVersion 36
		versionCode pluginVersionCode
		versionName pluginVersionName
		consumerProguardFiles("proguard-rules.pro")
	}
	buildTypes {
		debug {
			minifyEnabled false
		}
		release {
			minifyEnabled false
		}
	}
	buildToolsVersion '36.0.0'
	libraryVariants.configureEach { variant ->
		variant.outputs.all { output ->
			output.outputFileName = "GodotTenjin.$pluginVersionName.${variant.name}.aar"
		}
	}
}

dependencies {
	compileOnly "org.godotengine:godot:${godotVersion}.stable"
	compileOnly 'com.google.android.gms:play-services-ads-identifier:18.1.0'
	compileOnly 'com.android.installreferrer:installreferrer:2.2'
	compileOnly 'com.facebook.android:facebook-applinks:18.3.0'
	compileOnly 'com.tenjin:android-sdk:1.21.0'
}

tasks.register('buildIntoRelease', Copy) {
	group = "build"
	dependsOn tasks.build
	from([buildDir.absolutePath, 'outputs', 'aar'].join(File.separator))
	include("GodotTenjin.${pluginVersionName}.release.aar")
	into([rootDir.absolutePath, 'release/godot4'].join(File.separator))
}